version: '3'
services:
  app:
    build: .
    container_name: "bookshelf"
    ports:
      - "2300:2300"
    command: bundle exec hanami server --host 0.0.0.0
    volumes:
      - .:/home/bookself
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: "db"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-data: